### ISSUE TITLE
Installation: using QGIS "Manage and Install Plugins", or directions in the md file?

### ISSUE THREAD

**Issue by aloboa** [deepbands/buildseg#11]
What is better for Installation: using QGIS "Manage and Install Plugins", or following directions in the md file?
Using the QGIS installer (3.24.0-Tisler) I get:
An error occurred during execution of following code:
pyplugin_installer.instance().installPlugin('buildseg', stable=True)

Traceback (most recent call last):
  File "", line 1, in 
  File "/usr/share/qgis/python/pyplugin_installer/installer.py", line 333, in installPlugin
    self.processDependencies(plugin["id"])
  File "/usr/share/qgis/python/pyplugin_installer/installer.py", line 682, in processDependencies
    dlg = QgsPluginDependenciesDialog(plugin_id, to_install, to_upgrade, not_found)
  File "/usr/share/qgis/python/pyplugin_installer/qgsplugindependenciesdialog.py", line 92, in __init__
    _make_row(data, i, name)
  File "/usr/share/qgis/python/pyplugin_installer/qgsplugindependenciesdialog.py", line 63, in _make_row
    widget.use_stable_version = data['use_stable_version']
KeyError: 'use_stable_version'

Python version:
3.9.5 (default, Nov 18 2021, 16:00:48) 
[GCC 10.3.0]

QGIS version:
3.24.0-Tisler 'Tisler', 6b44a42058

Python path:
['/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/terminus_processing', '/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LAStools', '/usr/share/qgis/python', '/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python', '/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/home/alobo/OTB/OTB-7.3.0-Linux64/lib/python', '/usr/lib/python39.zip', '/usr/lib/python3.9', '/usr/lib/python3.9/lib-dynload', '/home/alobo/.local/lib/python3.9/site-packages', '/usr/local/lib/python3.9/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.9/dist-packages', '/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python', '.', '/home/alobo/.local/lib/python3.9/site-packages/IPython/extensions', '/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/site-packages', '/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin', '/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/qgispluginsupport/qps/pyqtgraph', '/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/site-packages', '/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/apps', '/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/coreapps']

**Comment by geoyee** [comment]
I am sorry for reply so long. This plugin is building by plugin builder, i think it is due to the new version of QGIS incompatible with the old version of plugin builder' plugin. We will pay attention to this issue.

**Comment by geoyee** [comment]
It could work in my 3.16.11.

**Comment by geoyee** [comment]
@aloboa ithink this issue was solved. see https://github.com/qgis/QGIS/pull/48208
